version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-stats-card
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Persist SQLite database
      - cache_data:/app/cache
      # Mount for development (uncomment for dev mode)
      # - .:/app
      # - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/cache/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development service (alternative to production)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: github-stats-card-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - cache_data:/app/cache
    restart: unless-stopped
    command: npm run dev
    profiles:
      - dev

volumes:
  cache_data:
    driver: local

networks:
  default:
    name: github-stats-network